server:
  port: 18082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.116.100:3306/guli_sms
    username: root
    password: root
  redis:
    host: 172.16.116.100
  sleuth:
    sampler:
      probability: 1
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.sms.entity
